function R = R1(alpha,belta,gama) 
R = [cos(belta)*cos(gama),sin(belta)*cos(gama),-sin(belta);
    sin(alpha)*sin(belta)*cos(gama)-cos(alpha)*sin(gama),...
    sin(alpha)*sin(belta)*sin(gama)+cos(alpha)*cos(belta),...
    sin(alpha)*cos(belta);
    cos(alpha)*sin(belta)*cos(gama)+sin(alpha)*sin(gama),...
    cos(alpha)*sin(belta)*cos(gama)-sin(alpha)*cos(belta),...
    cos(alpha)*cos(belta)];
